FROM r-base

WORKDIR /app

# Create output directory
RUN mkdir -p /app/output

RUN apt-get update && apt-get install -y \
    libgl1-mesa-dev \
    libx11-dev \
    libglu1-mesa \
    libfreetype6-dev \
    libxext-dev \
    libxrender-dev \
    xvfb \
    libcurl4-openssl-dev \
    libssl-dev \
    libxml2-dev \
    libpng-dev \
    pandoc \
    curl

# Install PhantomJS for plotly image export
RUN curl -L https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2 -o phantomjs.tar.bz2 && \
    tar -xvjf phantomjs.tar.bz2 && \
    mv phantomjs-2.1.1-linux-x86_64/bin/phantomjs /usr/local/bin/ && \
    rm -rf phantomjs*

# Install R libraries
RUN R -e "install.packages(c('ggplot2', 'plot3D', 'plotly', 'webshot2', 'htmlwidgets'), repos='http://cran.rstudio.com/')"

CMD ["Rscript", "/app/temp_code.R"]
