# Base image with python installed
FROM python:3.9-slim

# Set working directory inside the container
WORKDIR /app

# Create output directory
RUN mkdir -p /app/output

# Install required OS libraries for kaleido (Plotly Image Export)
RUN apt-get update && apt-get install -y libexpat1

# Install Python libraries
RUN pip install matplotlib plotly kaleido pandas numpy

# Default command (Overridden at runtime)
CMD ["python", "/app/visualization_code.py"]